### ISSUE TITLE
SuperInstructions Implementation

### ISSUE THREAD

**Issue by JeffersGlass** [JeffersGlass/cpython#1]
This is a blanket issue tracking information and goals for implementing SuperInstructions.

## Active Branches

- [`super-microops`](https://github.com/JeffersGlass/cpython/tree/super-microops) - Primary working branch
  - `super-microops-iterstats` Starting to work on getting the paircounts from pystats and using them to automatically update the supernodes ([see below](https://github.com/JeffersGlass/cpython/issues/1#issuecomment-2189750684))
  - [x]  `super-microops-paircount` Adding paircounts to the JIT itself. Could be pulled out and made a separate PR.
     - This was implemented and submitted as PR 120953 to CPython, from the branch `jit-uop-paircount`. The effects have been merged into super-microops. 
     - [ ] Merged into cpython/main?

## Implementation

- [x] Adjust `Tools/jit/build.py` and related to take accept a list of uops
- [x] Make JIT build tools accept supers from `executor_cases.c.h or similar`
- [x] Add SuperNodes to bytecode analyzer, emit them to ~`executor_cases.c.h`~ `supernode_cases.c.h`
  - [x] Make the analyzer aware of UOp oparg/operand/target overlaps like in [this PR](https://github.com/python/cpython/pull/119354)
- [x] Update uop ID and uop metadata generators to emit info for superinstructions
- [x] Write `jit_switch_generator.py` to generate a switch statement for given micro-ops
  - This goes into `jit_switch.c` and `jit_switch.h`, untracked on git
- [x] Write _PyJit_Combine to sythesize the oparg/operand/target from component UOps
- [x] Update `template.c` to accomodate 2+ uops
  - [ ] Investigate why clang isn't unrolling the switch statement...
  - [ ] Re-implement with switch statement for unlimited length superops
- [ ] Add additional points of `lltrace` debugging?
- [x] ~Move `jit_switch_generator.py` functionality directly into `build.py` etc to simplify jit regen.~ _`build.py` is for building stencils that are host specific, whereas the switch only depends on opcode choice. It should therefore live with the tier2 generator where it currently is._

### Testing + Finding SuperOps
[**See below**](https://github.com/JeffersGlass/cpython/issues/1#issuecomment-2189750684)

### Assorted TODOs:
- [x] Implement pair counting inside the JIT. See below.
- [ ] `analyzer.py`, `uop_metadata_generator.py` etc - Calculate stack properties of superinstructions
- [x] Change the format of SuperNodes in analyzer to not require an (unused) name.
- [ ] `tier2_generator.py` - We are no longer emitting `assert(oparg == CURRENT_OPARG()`, as that assumption is broken for superinstructions. Replace this this something that is valid (#define and #undef some sentinel?)
- [ ] `template.c` - clang isn't unrolling the switch statement as expected. Currently it has to be modified/generated to not use a switch... investigate if there's any way to fix this.

### Accomodating sequences where A+B+C always occur together

Let A, B, and C be UOps. If they _always_ (or almost always) occur in that sequence together, it would be good to include the superinstruction A+B+C but not A+B and B+C individually. Here's a 3-step process by which that could occur:

  - Run with pystats with no superinstructions `[]`. We'll see that A+B and B+C are common, so both are added to the list of superinstructions
  - Run with pystats with superinstructions `[AB, BC]`. We'll see that AB+C is common, so we should add it, but assuming we're chosing superinstructions greedily, we will never see A+BC nor BC by itself, so BC should be dropped.
  - Run with pystats with superinstructions `[AB, ABC]`. Because our selections go as deep as possible, we'll see ABC as common but AB will not occur, so it can be dropped.

Result: `[ABC]` is preserved as a superinstruction, but `AB` and `BC` are not.

## Pair Counting Inside the JIT

**Update:** Solved this with some modifications to the template.

Currently, pair counts are handled in the tier 2 interpreter using the `UOP_PAIR_INC` macro:
```c
#define UOP_PAIR_INC(uopcode, lastuop)                                              \
    do {                                                                            \
        if (lastuop && _Py_stats) {                                                 \
            _Py_stats->optimization_stats.opcode[lastuop].pair_count[uopcode]++;    \
        }                                                                           \
        lastuop = uopcode;                                                          \
    } while (0)
```
This relies on passing the current opcode (east) and the last opcode - easy in the tier 2 interpreter loop, but unknown at JIT compilation time.

One option would be to patch in the address of a new function like that would handle accessing/incrementing the last uop stored. This would want to be done in a threadsafe way. 

Update: It seems that even adding a new field `last_uop` to the PyExecutor struct (current_executor) and trying to access it causes a segfault. More investigation is necessary.

Update: This was implemented in the `JeffersGlass/jit-uop-paircount` branch and summitted as CPython PR 120953.

Update: Relevant to this - because the individual stencils are smashed together into Supernodes, even when supernodes are executed they are still tracked as the stats of their individual ops... HMMMMMMM.... that's a puzzle. Maybe need to move the pystats back out of the stencil???

Update: Solved.

**Comment by JeffersGlass** [comment]
As of e42bf60bc7899b6f6d51175538d4ef9d490359c9, there are some specific UOp pairs which cause segfaults when built into the JIT, specifically in `test_pstats`, `test_capi`, and `test_statistics`. My guess is that these relate to bad assumptions about debug/stats being on or off in the JIT, but not sure. The list includes:

- `_GUARD_BOTH_INT + _BINARY_OP_ADD_INT`

Some other pairs cause stats/optimizer tests to fail, including:
- `_UNPACK_SEQUENCE_TWO_TUPLE + _STORE_FAST_4`

**Comment by JeffersGlass** [comment]
# Automated Supernode Iteration

As described above, it will be necessary to iterate on the available superinstructions many times to build up longer superinstructions. This would benefit from automatically 

This work is being done in `JeffersGlass/cpython:super-microops-iterstats`.

## Todo:

- [x] Use functionality from `summarize_stats.py` to extract the uop pair data in a structured way. (*Implemented in `get_uop_pair_stats.py`)
- [ ] Apply filtering based one which UOps are compatible, i.e. don't have conflicting use of oparg/operand/target
  - *These are caught and rejected at JIT build time, but it would be nice to not emit them at all at this point/*
- [x] Apply filtering based on a set of "forbidden" UOps which break things
- [x] Select a set of superinstructions based on some criteria:
  - [x] Percentage of all uop pairs?
  - [ ] How many bytes the supernode saves in absolute terms, as in [this PR](https://github.com/python/cpython/pull/119693)?
  - [ ] How many bytes the supernode saves in relative terms?
- [x] Emit the changed set of supernodes directly into `supernodes.c`
- [x] Emit logging data showing which supernodes were added/removed in each step
- [ ] Emit `summarize_stats` at each phase as well 
- [x] Script an iterative process that:
  - [x] Rebuilds Python with new supernodes
    - [x] If the build fails, bisect (?) on supernodes to try to find which ones fail to build and exclude them
      - [ ] When bisecting, don't bother bisecting when the number is 3 ops or less, just try each of the three
      - [ ] If bisect fails during pystats run, extract the specific benchmark that caused the failure and just re-run that one
    - [ ] If the build fails, emit excellent logs on why/how
  - [x] regenerates stats 
  - [x] Generates a new set of supernodes
  - [x] Continues for a certain number of generations, or
  - [ ] until certain criteria are met.
- [ ] Output logs in a nondestructive way, 
- [ ] Process logs into some pretty graphs and stats

### Assorted thoughts/todos

- Consider re-implementing the build step using `pyperformance compile`
